---
- hosts: apache

  vars:
    domain: test.markbucciarelli.com

  tasks:

    - name: install Apache2
      package:
        name:
          - apache2
          - apache2-ctl
          - apache2-doc

    - name: enable mod_rewrite
      lineinfile:
        path: /etc/apache2/httpd.conf
        regexp: '^LoadModule rewrite_module '
        insertafter: '^#LoadModule rewrite_module '
        line: LoadModule rewrite_module modules/mod_rewrite.so
      notify:
       - restart apache2

    - name: create document root for virtual host
      file: path=/var/www/{{ domain }} state=directory

    - name: create log file directory for virtual host
      file: path=/var/www/logs/{{ domain }} state=directory

    - name: create virtual host file
      template: src=vhost.conf dest=/etc/apache2/conf.d/{{ domain }}.conf
      notify:
       - restart apache2

    - name: start apache if it is not running
      service: name=apache2 state=started

  handlers:
    - name: restart apache2
      service: name=apache2 state=restarted
