{application, json,
  [{description, "Produce JSON with Erlang"},
   {vsn, "1.0.0"},
   {modules, [log_event,
	      json,
	      json_sup,
	      json_handler]},
   {registered, []},
   {applications, [kernel, stdlib]},
   {mod, {json,[]}}]}.
